Removed StringBuffer use
cdk/cdk pull request #1135
Opened 2024-12-14 10:32 UTC by egonw

2024-12-16 02:40 UTC, uli-f commented
Unfortunately, this is not quite how it works.

To the best of my understanding there are two components to the optimization of `String` concatenations. The first one happens at compile time replacing those `String` concatenations with either `StringBuilder` calls (Java 8) or `StringConcatFactory` calls (Java >8). The second component is only implemented for Java >8 and takes place in the JVM translating those `StringConcatFactory` calls to a concrete String concatenation implementation of the JVM's choosing.

A prerequisite for this to work is that the compiler is able to optimize this at compile time. This is why concatenations carried out in loops cannot be optimized. More precisely,

```
String result = "";
for (int i = 0; i < 25; i++) {
  result = result + "counter=" + i;
}
```

This would result in one `StringBuilder` being instantiated for each concatenation in the loop. That's an improvement, but not the comprehensive optimization of only having a single `StringBuilder` for all concatenations.

When it comes to the use of other flow controls (conditional blocks, methods) I would assume that this cannot be determined at compile time either.

So in my understanding I would only use this in simple scenarios such as a locally confined concatenation:

```
public String toString() {
  return this.fieldA + this.fieldB + this.fieldC;
}
```

I apologize if my [previous explanation](https://github.com/cdk/cdk/pull/1133#issuecomment-2540658348) was cut too short and thus misleading.

refs
- https://howtodoinjava.com/java/string/string-concatenation-performance/
- https://marxsoftware.blogspot.com/2019/01/jep-280-indify-string-concatenations.html
- https://cl4es.github.io/2019/05/14/String-Concat-Redux.html

2024-12-16 09:25 UTC, johnmay commented
This patch probably should just be StringBuffer (synchronized) => StringBuilder

2024-12-16 12:14 UTC, uli-f requested changes
See general feedback in [comment](https://github.com/cdk/cdk/pull/1135#issuecomment-2544421355).

2024-12-16 12:16 UTC, uli-f commented
> This patch probably should just be StringBuffer (synchronized) => StringBuilder

I agree. Provided that thread-safety is not required for these classes

2025-02-06 04:47 UTC, uli-f commented
@egonw Do you want me to migrate that over to `StringBuilder` so that it can then be closed?

2025-02-08 06:19 UTC, egonw commented
> Do you want me to migrate that over to `StringBuilder` so that it can then be closed?

@uli-f, actually not sure. Since some sources suggest that in modern JVMs just using `"foo" + "bar"` can be optimized JIT pretty well, I was not entirely sure what the best approach is.

https://howtodoinjava.com/java/string/string-concatenation-performance/ writes:

```Since Java 9, String concatenation is a runtime decision, not a compile time one anymore. It means that after you the code Java 9 (or later) and it can change the underlying implementation however it pleases, without the need to re-compile.```

@johnmay, what do you think?

2025-02-08 09:34 UTC, johnmay commented
Well the String**Buffer** should go for sure, but I have no strong feeling on just using ``+`` vs a ``StringBuilder``. Personally here I would probably use ``StringBuilder`` here but this isn't going to be a performance critical so doesn't matter what is done.

My reading of that article is mainly on a simple cases bases.

>> *The invokedynamic call to java.lang.invoke.StringConcatFactory offers the facilities for a lazy linkage*

In this case the files has multiple concats at different parts I so I think it's unlikely to be able to optimise across those and a StringBuilder is likely better.

2025-02-08 09:43 UTC, egonw commented
@uli-f, conclusion: yes, please update to use the `StringBuilder`.

2025-02-08 11:45 UTC, uli-f commented
> @uli-f, conclusion: yes, please update to use the `StringBuilder`.

Okay, will migrate to `StringBuilder` then.

2025-02-25 12:17 UTC, johnmay commented
Super seeded by #1150

2025-02-25 12:17 UTC, closed without merging