apply patch from https://ip-147-251-124-124.flt.cloud.muni.cz/chemdb/sachem/
cdk/cdk pull request #688
Opened 2020-11-22 19:00 UTC by wolfgangcolsman

2020-11-22 20:37 UTC, johnmay commented
A lot of invalid characters causing the build to fail. Also I don't think a lot of the changes are OK without some discussion, or at least unit tests. Some are harmless but  random bits comment out for cis/trans in small rings, extra invariants added to canonicalisation (would break the default canon SMILES).

2020-11-22 21:48 UTC, johnmay commented
Hard to comment now due to reformatting on what I would accept wouldn't. Can you split them out in to seperate features else I'll just make A PR with the okay changes

2020-11-22 21:58 UTC, johnmay requested changes

2020-11-22 21:58 UTC, johnmay commented on base/core/src/main/java/org/openscience/cdk/atomtype/CDKAtomTypeMatcher.java
> +            if (bond.getOrder() != null && bond.getOrder().numeric() > max.numeric())
OK

2020-11-22 21:58 UTC, johnmay commented on base/core/src/main/java/org/openscience/cdk/config/IsotopeFactory.java
> +                switch(elem) {
Not OK need to be in the BODR and then compiled in @egonw can chime in. See slide 4 https://www.slideshare.net/NextMoveSoftware/building-on-sand-standard-inchis-on-nonstandard-molfiles on issues with InChI isotopes, e.g. Sg.

2020-11-22 21:58 UTC, johnmay commented on base/core/src/main/java/org/openscience/cdk/graph/Cycles.java
> +                final int threshold = 3072; // see. AllRingsFinder.Threshold.Pubchem_994
Sure but this may slow things down, it's a setting elsewhere that can be called with the looser value (3072) if needed.

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/aromaticity/DaylightModel.java
> +            bondOrderSum[i] = degree[i];
I don't see a benefit to moving this. Is fine but not useful

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/graph/invariant/Canon.java
> +        if (symmetry == null)
for empty molecules?

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/graph/invariant/Canon.java
> +            label <<= 10;
No, breaks the SmilesGenerator. Could be an option but we already have the option to use a comparator.

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +                                && centers.isStereocenter(w) /*&& !isInSmallRing(bond, 7)*/) {
No

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +                if (n == 2) return null;
Ok

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +                if (n == 4) return null;
Ok

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +            for (IBond bond : dbs)
Sure

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +            for (IBond bond : dbs)
actually no, the input may be wrong so we can't trust the "bond.getStereo()" setting

2020-11-22 21:58 UTC, johnmay commented on base/standard/src/main/java/org/openscience/cdk/stereo/StereoElementFactory.java
> +            if (container.getConnectedBondsCount(focus) != 2)
Ok

2020-11-22 21:58 UTC, johnmay commented on descriptor/cip/src/main/java/org/openscience/cdk/geometry/cip/rules/MassNumberRule.java
> +        if (isotope == null) return 0;
Ok, note Centres does a much better job of CIP labels. https://github.com/SiMolecule/centres

2020-11-22 21:58 UTC, johnmay commented on storage/ctab/src/main/java/org/openscience/cdk/io/MDLV2000Reader.java
> +            case 40:
sure

2020-11-22 21:58 UTC, johnmay commented on storage/ctab/src/main/java/org/openscience/cdk/io/MDLV2000Reader.java
> +                        container.getAtom(offset + index).setProperty(CDKConstants.SPIN_MULTIPLICITY, multiplicity);
Don't like this.

2020-11-22 21:58 UTC, johnmay commented on storage/ctab/src/main/java/org/openscience/cdk/io/MDLV2000Reader.java
> +                        container.getAtom(offset + index).setProperty(CDKConstants.SPIN_MULTIPLICITY, multiplicity);
Or more precisely, doesn't match the API. However it is how I would have done it if we could change the past :-)

2020-11-22 21:58 UTC, johnmay commented on storage/ctab/src/main/java/org/openscience/cdk/io/MDLV2000Reader.java
> +                    sgroup.putValue(SgroupKey.CtabLabel, line.substring(11).trim());
Don't think this is correct...

2020-11-22 22:08 UTC, wolfgangcolsman commented
Can you mane a PR with the OK changes and ignore the rest? This is just what I found at sachem, I cannot judge of the design details. Thank you.

2020-11-23 06:37 UTC, egonw commented
Hi @wolfgangcolsman, the purpose if splitting things out in separate patches and adding unit tests, is to ensure reviewers and future readers have enough information as content to see why the patch was made. I had a quick look yesterday, but hard a very hard time digesting it too and therefore did not comment yet. I didn't know where to start.

Manually splitting up this patch in parts is certainly something I could do, but then I still need to know why that patch is needed (what fails without it), what bits go together, etc.

I agree also with @johnmay's comment about the major isotopes, and added an inline comment about that.

So, let's get started. Let's start discussing the issues you ran into by first writing them down as a list or perhaps even one problem, one issue in the tracker?

2020-11-23 12:54 UTC, wolfgangcolsman commented
@egonw I am afraid I cannot help here, as I am not the author of the changes. I looked into sachem and found the changes in a patch file. Thought it might be useful to apply them, but do not understand the detail.

2021-01-18 11:05 UTC, johnmay commented
Resolved via #708 - thanks.

2021-01-18 11:05 UTC, closed without merging