Overflow logic was not quite correct. Restrict based on number of dig…
cdk/cdk pull request #810
Opened 2022-01-31 12:38 UTC by johnmay

…its, in base 10, 7 digits is enough for 9.9 million atoms which is more than enough for any molecule.

2022-01-31 12:39 UTC, johnmay commented
See comment on #808

2022-02-01 07:41 UTC, egonw requested changes

2022-02-01 07:41 UTC, egonw commented on tool/formula/src/test/java/org/openscience/cdk/tools/manipulator/MolecularFormulaManipulatorTest.java
>                  is(2147483647));
Maybe update the line too to expect 10000000? I know that for the test it won't matter, but will surely not freak out people in the future reading the code :)

2022-02-01 08:19 UTC, johnmay commented
Fixed

2022-02-01 08:36 UTC, merged